name: First Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Welcome Message
              run: echo "Welcome to GitHub Actions"
            - name: List Files
              run: ls -la
            - name: Read File
              run: cat README.md
