name: Reusable Workflow

on:
    workflow_call:
        inputs:
            name:
                required: true
                type: string
                description: Name of the person to greet

jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
            - name: Greet the user
              run: echo "Hello ${{inputs.name}}"
