name: Upload and Download Artifacts Practice

on: push

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: Run Shell Script
              run: |
                  chmod +x ascii-script.sh
                  ./ascii-script.sh

            - name: Upload the artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dragon-text
                  path: dragon.txt
    download:
        needs: upload
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: Download the artifact
              uses: actions/download-artifact@v4
              with:
                  name: dragon-text
            - name: read the dragon file
              run: cat dragon.txt
