name: Variable & Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: motinxyz
    IMAGE_NAME: github-actions-nginx
    WF_ENV: workflow

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            JOB_ENV: job
        steps:
            - name: Docker Build
              env:
                  STEP_ENV: step
              run: |
                  echo docker build -t ${{env.WF_ENV}}/${{env.JOB_ENV}}/$STEP_ENV:latest
                  echo secrets pulled in from repo level: ${{secrets.DOCKER_PASS}}
                  echo repo variables ${{vars.CONTAINER_REGISTRY}}
